### PR TITLE
Call garbage-collect through async route

### LINKED ISSUE #221: Asynchronous invocation of garbage-collect
Currently in `github-event` we invoke `garbage-collect` in the synchronous route e.g. `/function/garbage-collect` which time outs in case we delete the whole application and we have couple of repositories installed on the cloud.

## Expected Behaviour

We should call garbage-collect from the asynchronous route e.g. `/async-function/garbage-collect` to handle the case where we uninstall the whole openfaas-cloud application and we have more then one repositories.

## Current Behaviour

We call the function in the synchronous route e.g. `/function/garbage-collect` and it will timeout if we have couple of repositories

## Possible Solution

Invoke garbage-collect from the asynchronous route

## Steps to Reproduce (for bugs)

1.Install OF-cloud application on couple of repositories
2.Wait for your functions to be deployed
3.Uninstall whole app
4.See you still have functions on the cloud

## Context

For the times a user would like to remove his functions from the cloud and we want to automate the process.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.06.0-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Docker Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N.A. try with public cloud if you have access
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by martindekov**
Calling garbage-collect through async route in github-event
so the request wont time out in case we have couple of functions
deployed

Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>

## Description

This is small tweak that enables calling garbage-collect through async route for the times user with couple of functions want to uninstall the application and delete all its functions from the cloud.

Closes #221 

## How Has This Been Tested?

All function deleted with logs logs 
```
...
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Need to remove: martindekov/bottester.
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Need to remove: martindekov/goforfun.
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Need to remove: martindekov/gocloudfunc.
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Need to remove: martindekov/cloudlogo.
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Need to remove: martindekov/kubernetesgo.
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Status code for garbageCollect: 202
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Status code for garbageCollect: 202
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Status code for garbageCollect: 202
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Status code for garbageCollect: 202
system-github-event.1.w4bvfwjy9l3l@FaasSwarm    | Status code for garbageCollect: 202
...
```

## How are existing users impacted? What migration steps/scripts do we need?

No migration needed, just added feature.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
```
		if res.StatusCode != http.StatusOK {
```

We should check for 202 in this instance, StatusAccepted (only)

**Comment by alexellis** [comment]
Perhaps we should also include the status code in the message - this would have helped you in this instance.

File: github-event/handler.go [hunk 1]
```diff
@@ -168,7 +168,8 @@ func garbageCollect(garbageRequests []GarbageRequest) error {
 		if res.Body != nil {
 			defer res.Body.Close()
 		}
-		if res.StatusCode != http.StatusOK {
+		fmt.Printf("Status code for garbageCollect: %d\n", res.StatusCode)
```
Comment (alexellis) [inline github-event/handler.go]: Only `log.Printf` if this is not the desired status code?

Comment (martindekov) [reply github-event/handler.go]: This the status code for every request printed since you had comment above that its good idea to print all the status codes to check whats up with every request `Perhaps we should also include the status code in the message - this would have helped you in this instance.`  I think that's what you meant.

Comment (ivanayov) [inline github-event/handler.go]: You can add 
`garbageRequest.Owner/Repo` so that the message can point to the GC-ed function

**Comment by martindekov** [comment]
Referenced your comment @ivanayov . Now I give repo - status code.
