### PR TITLE
Move customer validation into github-event

### LINKED ISSUE #163: Move CUSTOMERS validation out of github-push
Soon we would like to move out of `github-push` for event handling and support more than push events from github and give that to `github-event`. Currently the CUSTOMER validation is handled in `github-push`

## Expected Behaviour

Should extend the `PushEvent` struct with `sender` field to compare by that since the field is present in the outer layer of `X-GitHub-Event: push`,`X-GitHub-Event: installation_repositories` and `X-GitHub-Event: integration_installation_repositories`.

## Current Behaviour

We handle the situation in `github-push` by struct which is unique to the push event.

## Possible Solution

Move the CUSTOMERS handle out of github-push into github-event and create separate struct or extend existing struct which handles events so it can compare by `event.Sender.Owner` rather than more specific `event.PushEventRepository.Owner.Login` since every event contains
```
...
    "sender": {
        "login": "martindekov",
...
```

## Steps to Reproduce (for bugs)

N.A. 

## Context

If we want the `github-event` function to handle the redirection we cant contain CUSTOMERS validation in `github-push`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

18.06.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):

Ubuntu 18.04

* Link to your project or a code example to reproduce issue:

N.A.

### PR DESCRIPTION
**Pull request by martindekov**
Moving customer validation out of github-push
and into github-event depending on commit #271

Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>

## Description

This commit extends #271 and if merged closes #163. Currently the build fails since the struct is not vendored.

> Note: Not sure if the `Customers` struct in #271 would be used elsewhere. Should I add it into the handler directly? 

Also added additional check for `\r` since if making changes to a file through github UI it will append `\r\n` to the end of the line rather than only `\n` as expected. I personally have separate repository that contains my customers for faster updating.

## How Has This Been Tested?

Have the change in image `martindekov/github-event:163` and deployed image on my instance.

Added my own Customers file and tested with case sensitive name existing in the file
```
Push - {refs/heads/master {exmpl MartinDekovWat/exmpl https://github.com/MartinDekovWat/exmpl.git false {MartinDekovWat 42210992+MartinDekovWat@users.noreply.github.com}} d86e067fc83d4ada19ce05cdf5edc141d35d0076 {312235}}, git-tar status: 202
```
And my account non existing in file
```
Customer: martindekov not found in CUSTOMERS file via https://raw.githubusercontent.com/martindekov/mycustomers/master/CUSTOMERS
```

## How are existing users impacted? What migration steps/scripts do we need?

N.A. moving logic out of the `github-push`

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by ivanayov** [comment]
The build fails with `function/handler.go:51:15: undefined: sdk.Customer`
You need to take #271

**Comment by alexellis** [comment]
@martindekov why does this fail the CI?

**Comment by martindekov** [comment]
Because this extends #271 once merged I will vendor the SDK and it wont fail.

**Comment by martindekov** [comment]
Ah ok I will

**Comment by ivanayov** [comment]
Looks good

**Comment by alexellis** [comment]
Looks ready to merge.

File: github-event/handler.go [hunk 1]
```diff
@@ -238,3 +268,56 @@ func forward(req []byte, function string, headers map[string]string) (string, in
...
+			break
+		}
+	}
+
+	return found
+}
+
+// getCustomers reads a list of customers separated by new lines
+// who are valid users of OpenFaaS cloud
+func getCustomers(customerURL string) ([]string, error) {
```
Comment (alexellis) [inline github-event/handler.go]: How is this different from what we do for Derek? Can you take a look and compare?

File: github-event/handler.go [hunk 2]
```diff
@@ -37,6 +38,35 @@ func Handle(req []byte) string {
...
+	if readBool("validate_customers") {
+		customersURL := os.Getenv("customers_url")
+
+		customers, getErr := getCustomers(customersURL)
+		if getErr != nil {
+			return getErr.Error()
+		}
+
+		customer := sdk.Customer{}
+		json.Unmarshal(req, &customer)
```
Comment (bartsmykla) [inline github-event/handler.go]: There is missing error handling

File: github-event/handler.go [hunk 3]
```diff
@@ -37,6 +38,35 @@ func Handle(req []byte) string {
...
+
+		found = validCustomer(customers, customer.Sender.Login)
+
+		if !found {
```
Comment (bartsmykla) [inline github-event/handler.go]: Instead of `if !found {` you can do:
```
if !validCustomer(customers, customer.Sender.Login) {
```

File: github-event/handler.go [hunk 4]
```diff
@@ -238,3 +268,56 @@ func forward(req []byte, function string, headers map[string]string) (string, in
...
+	for _, customer := range customers {
+		if len(customer) > 0 &&
+			strings.EqualFold(customer, owner) {
+			found = true
+			break
+		}
+	}
+
+	return found
+}
```
Comment (bartsmykla) [inline github-event/handler.go]: I would write it:
```
func validCustomer(customers []string, owner string) bool {
	for _, customer := range customers {
		if len(customer) > 0 && strings.EqualFold(customer, owner) {
			return true
		}
	}

 	return false
}
```

File: github-event/handler.go [hunk 5]
```diff
@@ -238,3 +268,56 @@ func forward(req []byte, function string, headers map[string]string) (string, in
...
+
+	if res.Body != nil {
+		defer res.Body.Close()
+
+		pageBody, _ := ioutil.ReadAll(res.Body)
+		customers = strings.Split(string(pageBody), "\n")
+
+		for i, c := range customers {
+			customers[i] = strings.ToLower(c)
+			customers[i] = strings.TrimSuffix(c, "\r")
```
Comment (bartsmykla) [inline github-event/handler.go]: There is something wrong, you are assigning value and then immediately overriding it

File: github-event/handler.go (hunk 4 above)
Comment (martindekov) [reply github-event/handler.go]: Done ^

File: github-event/handler.go (hunk 5 above)
Comment (martindekov) [reply github-event/handler.go]: Yep this was irrational 😄

File: github-event/handler.go (hunk 3 above)
Comment (martindekov) [reply github-event/handler.go]: Good idea!

**Comment by martindekov** [comment]
I amended some fixes, I haven't looked into the function I just moved the logic out. Also added more detailed reports since those were only from the requests. Thanks for the feedback @bartsmykla really helped out
