### PR TITLE
Link to SCM and public key in dashboard

### LINKED ISSUE #697: Link to GitHub app from dashboard
Users of an OpenFaaS Cloud cluster currently need to obtain the link of the GitHub app out of band.
Linking to the app in the dashboard would make the [installation step](https://docs.openfaas.com/openfaas-cloud/user-guide/#install-the-github-app) easier.

## Expected Behaviour

Ofc users can find the GitHub app to install via the dashboard

## Current Behaviour

Link to app is obtained out of band

## Possible Solution

Repurpose the dashboard icon linking to the openfaas-cloud github repo
https://github.com/codius/openfaas-cloud/commit/d52554f0249ed37922d761b1e2ea27037e884e9e

## Steps to Reproduce (for bugs)

1. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by wilsonianb**
## Description
Resolves #697 
Dashboard links to GitHub app or GitLab instance and serves secrets public key if configured.

## How Has This Been Tested?

Followed ofc-bootstrap user guide using the changes in https://github.com/openfaas/ofc-bootstrap/pull/240 along with this [patch](https://github.com/wilsonianb/ofc-bootstrap/commit/d2621e8d0f145091505407f4412f417bc0f8155f) to install ofc on k3s.
Ran each of the following once with [`scm`](https://github.com/openfaas/ofc-bootstrap/blob/e16b776a352f9727594eba79af0f9b2bd0e2d8bb/example.init.yaml#L236-L237) as `github` and again as `gitlab`:
```
ofc-bootstrap apply --file init.yaml  --skip-sealedsecrets
ofc-bootstrap apply --file init.yaml
```
The deployed dashboard includes the correct icons and links based on the configuration

## How are existing users impacted? What migration steps/scripts do we need?
Setting up a repo with ofc and encrypting secrets should be easier.
The [user guide](https://docs.openfaas.com/openfaas-cloud/user-guide/) (linked to from the dashboard) and [secrets](https://docs.openfaas.com/openfaas-cloud/secrets/) docs pages could be updated to highlight the new dashboard links.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Please could we have a screenshot?

**Comment by alexellis** [comment]
Does it also handle GitLab when configured?

**Comment by wilsonianb** [comment]
Live dashboards:
[GitHub + Public Key](https://system.k3s.codiusfaas.net/dashboard/alice)
[GitLab](https://system.demo.codiusfaas.net/dashboard/alice)

**Comment by alexellis** [comment]
For the next stage I'm thinking a page that shows the key and gives the sample command for using it.

**Comment by alexellis** [comment]
The GitLab link didn't have the key shown?

**Comment by wilsonianb** [comment]
>The GitLab link didn't have the key shown?

That dashboard isn't configured with a public key, which is what would happen if ofc-bootstrap were run with
```ofc-bootstrap apply --file init.yaml  --skip-sealedsecrets```

File: dashboard/of-cloud-dashboard/handler.js [hunk 1]
```diff
@@ -76,6 +76,18 @@ module.exports = async (event, context) => {
     headers['Content-Type'] = 'application/json';
   } else if (/.*\.map/.test(path)) {
     headers['Content-Type'] = 'application/octet-stream';
+  } else if (/^\/dist\/pub-cert.pem\/?$/.test(path)) {
```
Comment (alexellis) [inline dashboard/of-cloud-dashboard/handler.js:79]: I think it might be useful to serve the key from the dashboard. Perhaps we can export the key during the setup and have it attached as as secret to the dashboard container?

Comment (alexellis) [reply dashboard/of-cloud-dashboard/handler.js:79]: `/api/public-key.pem` <- it could then serve this value

File: dashboard/dashboard_config.yml [hunk 2]
```diff
@@ -11,4 +11,39 @@ environment:
...
-  cookie_root_domain: 'system.o6s.io'
\ No newline at end of file
+  cookie_root_domain: 'system.o6s.io'
+  # Public URL for your GitHub app
+  # see https://github.com/settings/apps/
+  # github_app_url: https://github.com/apps/o6s-io
+  # Public URL for your GitLab instance
+  # gitlab_url: https://gitlab.o6s.io/
+  # SealedSecrets public key
+  # public_key: |
```
Comment (alexellis) [inline dashboard/dashboard_config.yml:21]: I'm less keen on this approach. I think using a K8s secret would work better and be easier to maintain.

**Review by Waterdrips — APPROVED** [review]

**Review by alexellis — APPROVED** [review]
Approved
