### PR TITLE
Edit findStackFile to form raw URL depending on GitHub/GitLab

### LINKED ISSUE #276: Edit git-tar raw URL stack file optimisation to support both GitHub/GitLab
This commit https://github.com/openfaas/openfaas-cloud/commit/aa5828702f0e82f5b1070cb1c1b73ff908ceb4e3 adds optimization for git-tar but I think the format of the URL in this line https://github.com/openfaas/openfaas-cloud/commit/aa5828702f0e82f5b1070cb1c1b73ff908ceb4e3#diff-6972f28fc33acdd0e2082babf8ec8405R276 should be moved away from git-tar possibly sent through github-push or github-event to the git-tar so the function itself is non dependent on github or any SCM

## Expected Behaviour

URL to be formatted in github-push or github-event rather than git-tar. Move away SCM specific field out of git-tar.

## Current Behaviour

Git-tar suggest only github raw formatting

## Possible Solution

Format the URL in github-event or github-push function and send it to git-tar.

## Steps to Reproduce (for bugs)

It is not a bug per se

## Context

It is currently blocking #275 since the format of the URL is wrong for gitlab. And the workaround I am currently using is to set the `private_repo:true` all the time for gitlab, which is not the case. Also I think it is a good thing to keep functions down from git-tar away from SCM specific code.

### PR DESCRIPTION
**Pull request by ivanayov**
The raw URL for stack.yml was previously supporting only GitHub, so the build was failing for GitLab. With this change raw URL is properly formed depending on the git hosting solution  (GitHub/GitLab)

Signed-off-by: Ivana Yovcheva <iyovcheva@vmware.com>

Closes #276

## How Has This Been Tested?

Tested by @martindekov on GitLab
I tested on GitHub:
1. Succeeds when stack.yml is available
2. Fails when not with `unable to find stack.yml`
3. After reproducing error with empty raw url (by using an image for `github-push` without the changes) fails with `given stack file raw URL is empty`. This resolves previous problem in behaviour - if fileSTackFile fails with error, there were no status reported.

## How are existing users impacted? What migration steps/scripts do we need?
Not impacted

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests N/A

### CODE REVIEW

**Comment by martindekov** [comment]
Tested by deploying image provided by @ivanayov  with the change the following scenario deployed gitlab-push in `gitlab.yml` with option: 
```
      private_repo: false
```
(before had to workaround this by setting `private_repo: true`) and it built my function successfully.
Also amended #109 to use the solution.

**Comment by alexellis** [comment]
For GitLab could we look at the "Repo URL" from the push event and use that to create the URL for the stack.yml?

**Comment by martindekov** [comment]
This is connected with Issue that I am assigned to #210 and I will open PR and explain here how to extend/remake this PR with the change.

**Comment by martindekov** [comment]
So @ivanayov I have opened PR #291 which fixes the issue pointed above in the proper way.
In `git-tar` get `event.SCM` field and check `github-push`? if so construct in the URL in github manner. For gitlab since we have custom URL I might need to add another field/function to construct the URL I think https://github.com/martindekov/openfaas-cloud/commit/20c6b09edf03a329aff676195f1827ed1a7949f2 may be used to construct the URL

File: git-tar/function/handler.go [hunk 1]
```diff
@@ -266,14 +271,26 @@ func reportStatus(status *sdk.Status) {
 // available via the CDN. Note: given that the CDN has a 5-minute timeout - this optimization
 // may have the undesired effect of preventing a user from deploying within a 5 minute window
 // of renaming an incorrect "function.yml" to "stack.yml"
-func findStackFile(repo *sdk.PushEventRepository) (bool, error) {
+func findStackFile(pushEvent sdk.PushEvent) (bool, error) {
```
Comment (alexellis) [inline git-tar/function/handler.go]: Why did we remove the pointer reference? Should add it back to not copy by value.

Comment (alexellis) [inline git-tar/function/handler.go]: How has this been unit tested? I'd like to see unit tests for this as part of the PR.

File: git-tar/function/handler.go [hunk 2]
```diff
@@ -296,3 +305,22 @@ func findStackFile(repo *sdk.PushEventRepository) (bool, error) {
 
 	return false, nil
 }
+
+func getRawURL(scm string, repositoryURL string, repositoryOwnerLogin string, repositoryName string) (string, error) {
+
+	addrPrefix := ""
+	rawPath := ""
+	switch scm {
```
Comment (alexellis) [inline git-tar/function/handler.go]: `scm` stands for source control management - so this should be only `github` or only `gitlab`. Not sure why we are adding the text `-push` here? Please change.

File: git-tar/function/handler_test.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
+package function
+
+import (
+	"testing"
+)
+
+func Test_getRawURL(t *testing.T) {
```
Comment (alexellis) [inline git-tar/function/handler_test.go]: Good to see the tests.

File: git-tar/function/handler.go (hunk 2 above)
Comment (ivanayov) [reply git-tar/function/handler.go]: These are the values that come from pushEvent.SCM. 
We need to change them in order to omit the `-push` suffix here

Comment (martindekov) [reply git-tar/function/handler.go]: I added the change but directly with `Source` constant. This can be quickly changed.

**Comment by ivanayov** [comment]
@alexellis I've updated the scm field

File: git-tar/vendor/github.com/openfaas/openfaas-cloud/sdk/events.go [hunk 4]
```diff
@@ -20,6 +20,7 @@ type PushEvent struct {
 	Repository    PushEventRepository
 	AfterCommitID string `json:"after"`
 	Installation  PushEventInstallation
+	RepositoryURL string `json:"url"`
```
Comment (martindekov) [inline git-tar/vendor/github.com/openfaas/openfaas-cloud/sdk/events.go]: This should be inside `PushEventRepository` struct

Comment (martindekov) [inline git-tar/vendor/github.com/openfaas/openfaas-cloud/sdk/events.go]: This should be inside `PushEventRepository` struct

**Comment by ivanayov** [comment]
@martindekov , I've updated the url

**Comment by alexellis** [comment]
Merged
