### PR TITLE
Make Github Status namespace checks by APP ID

### LINKED ISSUE #540: [Enhancement] Support multiple OFC apps per repository
## Expected Behaviour

I would like to be able to have a repository built and deployed onto multiple OFC installations and see the build status set successfully for each app on each commit.

## Current Behaviour

The integration with multiple OFC installations is not great - It works but does not report back that the deployment was successful and you only see each "build" step in 1 app. (screenshot)
image

## Possible Solution

namespace the build steps to the cluster or something so they can appear under both apps

## Steps to Reproduce (for bugs)

1. Add multiple OFC integrations to a repository
2. Trigger a build

## Context

commits always sit in pending status and dont succeed.

## Your Environment

OFC Community and OFC personal, through Github integration

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

The Github Status function was not namespacing the check-runs. It was
using the same ting for each installed app. This has been changed to
namespace by app_id. This means that 2 + installations on the same
repository can now correctly create & report github check runs.

Fixes #540 

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## How Has This Been Tested?

This has been tested by installing 2x OCF installations, then running a
pipeline. This failed of half of the functions as they didn't get the
correct check for that app.

Then I added the new function to each OFC installation, and re-ran a
pipeline. Every check run was created and reported back correctly.

## How are existing users impacted? What migration steps/scripts do we need?
Users with more than 1 app installed can correctly get statuses back from the OFC installations.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

File: github-status/handler.go [hunk 1]
```diff
@@ -119,21 +119,23 @@ func getLogs(status *sdk.CommitStatus, event *sdk.Event) (string, error) {
 }
 
 func reportToGithub(commitStatus *sdk.CommitStatus, event *sdk.Event) error {
+	appID := os.Getenv("github_app_id")
 	if os.Getenv("use_checks") == "false" {
-		return reportStatus(commitStatus.Status, commitStatus.Description, commitStatus.Context, event)
```
Comment (alexellis) [inline github-status/handler.go:123]: What kind of value was in `commitStatus.Context` before vs the static GitHub app ID?

Comment (Waterdrips) [reply github-status/handler.go:123]: https://developer.github.com/v3/repos/statuses/

```
context | string | A string label to differentiate this status from the status of other systems. Default: default
```

`default` was always the value

Comment (alexellis) [reply github-status/handler.go:123]: OK, so did you pick the GitHub app ID because it should be unique between installations? It could be any identifier as long as it is consistent?

Comment (Waterdrips) [reply github-status/handler.go:123]: Yeh, and its already included in the image as an env var

**Comment by Waterdrips** [comment]
@alexellis any thoughs on merging this?
